sudo: false
language: node_js
node_js: 8.1

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

env:
  global:
  - CXX=g++-4.8
  - NODE_ENV=production
  - secure: gJ/oIV6viUzpiUZdLJfgYPwF0JQDxCfq/P2Ya1KgvXhuZQJ4ns6zMbp6ccVd4KTOYOY5BXy1NRBuP1vcPyfaZ60bCuLXTMX35+5mbeK4apuC9JK3AaMd+aLLupYN79YDnd839vDhoMppdXYWV+V7Q+HrwKaANST+J5t84LvcYVNbo/4BwWntlaHenacr0Aklhr2d6X4qPTeTSpfalvTBXazSj/lJHqlv0XCXfYez4bMZPMvFPvOPNzrn6fSK0K/i7rKVY5R0vsueKDjQA9RYA7ywCtNDLDW4pza+GhSh2PtgOjlLUVGr24ToFkQfWGN2OaAT0+/+MnQd8fMy7OoIJGOmX6PA9EQtIx5Z9FfjRCiBg+4eaMQN5Ql6CNzE/oDYi+7NhTsfxmhl/0aP5CCjFDVnx+WJTsUyIPmTXQJbnxT3z5YPUWoNFArMKX+3pWIUnezVd4zvn7+R0yDB3Z37T5zZLJwlw1bmIXukMqM115vfGkBp27c5FIMaNmulQ7c/jaJ+A8g+Qhjqzf9WMdKEkPoKBRxmI+vDD0nx/D3tyOaMxGPbiTYjPqeCbJafdwM122pkPwBeP0dP+pptPdqiyXGLllFj5RrSjoSniDZalJt8alqZnM9wJaef60IBxOikQmJnHMtgcAtkxcAqnRvEDl3T3Lw2YzWUSSqHXwUHrJk=
  - secure: "lkfKY0zApN1k53uvqLZytz/rzIBhNXffD2/Xb2FGBpwjIzZbrqNLBwa3dPteoPTuQ1aIvpmbGetAJSiSrepLUuv6eX/dluC49d1CIWDImduac+4daA+o3aEED5Ngvx/M/TrDdF/wRk3e/PhlGKPz9M+oAxvp1xNuXpCDf66hFoRzU6UfvL1p8Yqih7RyF//9ZwZauAdAjQXr/nT/I7cY2h/+5PCqrL17znuqPEgy+HOVoFeuOUP/LJDggdCmW6E/D5ZqK2ceDYsCkleVBYAvkAffVb/PQCrcxAKkF6Oir947czH+L1OUWFopzCXE55M15arm/jkL2FD8u7/DknhuyH1WPrTrWu5PRpZLb0aKyHHHVJiLRYu4i8WtJLHJzwg34DQSJHBQ8JhBxNl7HZZbhjQMk9mCWeiZHbwKghLiiwzO5Ef9IRATSAzhCBoUPqRZjBg+cHw3odt8PjCdM8ayZOP8lshnLWcy25w8E0fyQJRLMbR8GmSTp1SkhT/Gt7i34eX6RsQLaOZHUT3c1vltxjAhP2iB5DjygTinlVzDsfb6cFvk9U0Ot63Hjnc5f3nXuxsDzQuFlIbV5vari9jiz5zaBw8QbDJz5RcRP7Uua4L6JZFyWD6OePC61jkdYUWnR58V68Pt2Zhjy2TR5NN9ndTgiX2EjJvg9kUfZPvuHxc="

cache:
  yarn: true
  directories:
    - node_modules

install:
- yarn install --production=false

after_success:
- "./scripts/deploy-gh-pages.sh"
