name: Node.js CI

on: [push]

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    env:
      NODE_ENV: production

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 8

      - uses: actions/setup-python@v4
        with:
          python-version: 3.13.3

      - name: Cache node modules
        uses: actions/cache@v4
        with:
          path: ~/node_modules
          # Look to see if there is a cache hit for the corresponding requirements file
          key: ${{ runner.os }}-yarn-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
            ${{ runner.os }}-

      - run: yarn install --production=false
      - run: yarn test

      - name: Deploy with gh-pages
        if: github.ref == 'refs/heads/master'
        run: |
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          yarn deploy -- -u "github-actions-bot <support+actions@github.com>" -b master -r https://git:${OTHER_REPO_GITHUB_TOKEN}@github.com/golmansax/golmansax.github.io.git
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OTHER_REPO_GITHUB_TOKEN: ${{ secrets.OTHER_REPO_GITHUB_TOKEN }}
